style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/marcincuber/terraform-aws-ssm-parameters
options:
  header:
    pattern: "^(.*)$"
    pattern_maps:
      - Subject